import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/components/navbar";
import { Dancing_Script } from "next/font/google";
import FooterComponent from "@/components/footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const dancingScript = Dancing_Script({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // elige los pesos que necesites
  variable: "--font-dancing-script",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "IBRAV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={dancingScript.variable}> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-dancing`}
      >
        <NavbarComponent/>
        {children}
        <FooterComponent/>
        <ToastContainer />
      </body>
    </html>
  );
}
